"""redid models

Revision ID: 44fc94836fdd
Revises: c6bfbe9a18e9
Create Date: 2023-04-18 11:35:53.925458

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44fc94836fdd'
down_revision = 'c6bfbe9a18e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attacks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pirate_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('ship_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_attacks_pirate_id_pirates'), 'pirates', ['pirate_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_attacks_ship_id_ships'), 'ships', ['ship_id'], ['id'])

    with op.batch_alter_table('pirates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rank', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.drop_constraint('fk_pirates_ship_id_ships', type_='foreignkey')
        batch_op.drop_constraint('fk_pirates_attack_id_attacks', type_='foreignkey')
        batch_op.drop_column('ship_id')
        batch_op.drop_column('attack_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pirates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('attack_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('ship_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_pirates_attack_id_attacks', 'attacks', ['attack_id'], ['id'])
        batch_op.create_foreign_key('fk_pirates_ship_id_ships', 'ships', ['ship_id'], ['id'])
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('rank')

    with op.batch_alter_table('attacks', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_attacks_ship_id_ships'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_attacks_pirate_id_pirates'), type_='foreignkey')
        batch_op.drop_column('ship_id')
        batch_op.drop_column('pirate_id')

    # ### end Alembic commands ###
